# Generated by Django 4.1.2 on 2022-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='budget',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='first',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ] #новая миграция
