# Generated by Django 4.1.2 on 2022-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0002_first_budget_first_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
