# Generated by Django 4.1.2 on 2022-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0003_first_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='currency',
            field=models.CharField(choices=[('Man', 'Man'), ('Women', 'Women')], default='Man', max_length=5),
        ),
        migrations.AlterField(
            model_name='first',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
