# Generated by Django 4.1.2 on 2022-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0005_alter_first_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
