# Generated by Django 4.1.2 on 2022-11-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0007_alter_first_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensei_name', models.CharField(default='Джеки', max_length=100)),
                ('sensei_famale', models.CharField(default='Чан', max_length=100)),
            ],
        ),
    ]
