# Generated by Django 4.1.2 on 2022-11-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0008_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sql_start.second'),
        ),
    ]
