# Generated by Django 4.1.2 on 2022-11-03 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0009_first_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sql_start.second'),
        ),
    ]
