# Generated by Django 4.1.2 on 2022-11-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0011_third_first_third'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('cabinet', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='third',
            name='ford',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sql_start.ford'),
        ),
    ]
