# Generated by Django 4.1.2 on 2022-12-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0013_hh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adress', models.TextField()),
                ('photo', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
