# Generated by Django 4.1.2 on 2022-12-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0015_cities_hotels_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
