# Generated by Django 4.1.2 on 2022-12-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_start', '0021_cities_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
